name: morkovka
type: laravel
docroot: backend/public
php_version: "8.2"
router_http_port: "8000"
router_https_port: "8443"
database:
  type: postgres
  version: "15"
use_dns_when_possible: true
additional_hostnames:
  - morkovka-frontend
