version: '3.6'
services:
  frontend:
    image: node:18
    container_name: ddev-${DDEV_SITENAME}-frontend
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html:cached
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
